# Generated by Django 4.2.5 on 2023-10-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multipleimages',
            options={'verbose_name_plural': 'Multiple Images'},
        ),
    ]
