# Generated by Django 4.2.5 on 2023-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_multipleimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
