# Generated by Django 4.2.5 on 2023-11-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
