# Generated by Django 4.2.5 on 2023-11-10 05:45

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image_crop',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='category_images/'),
        ),
    ]
