# Generated by Django 4.2.5 on 2023-11-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_category_category_image_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image_crop',
        ),
    ]
