# Generated by Django 4.2.5 on 2023-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_remove_category_category_image_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='offer',
        ),
    ]
