# Generated by Django 4.2.5 on 2023-10-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_cart_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
