# Generated by Django 4.2.5 on 2023-10-20 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_coupons_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='coupon_title',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='coupons',
            name='min_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coupons',
            name='valid_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
