# Generated by Django 4.2.5 on 2023-10-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_remove_coupons_coupon_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='min_amount',
            new_name='minimum_order_amount',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='valid_at',
            new_name='valid_to',
        ),
    ]
