# Generated by Django 4.2.5 on 2023-10-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_alter_coupons_valid_from_alter_coupons_valid_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name_plural': 'Coupons'},
        ),
    ]
