# Generated by Django 4.2.5 on 2023-10-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0013_alter_coupons_active_alter_coupons_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='description',
        ),
    ]
