# Generated by Django 4.2.5 on 2023-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0015_coupons_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
