# Generated by Django 4.2.5 on 2023-10-06 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('alternative_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('town', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('nearby_location', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
