# Generated by Django 4.2.5 on 2023-10-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address'},
        ),
    ]
