# Generated by Django 4.2.5 on 2023-10-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_useraddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User Address'},
        ),
    ]
