# Generated by Django 4.2.5 on 2023-10-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_customuser_date_of_birth_customuser_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='nearby_location',
            new_name='Landmark',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='zip_code',
            new_name='pincode',
        ),
    ]
