# Generated by Django 4.2.5 on 2023-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_nearby_location_useraddress_landmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='town',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='Landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
