# Generated by Django 4.2.5 on 2023-10-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_useraddress_town_useraddress_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='Landmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='alternative_mobile',
            new_name='mobile',
        ),
    ]
