# Generated by Django 4.2.5 on 2023-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_rename_landmark_useraddress_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
