# Generated by Django 4.2.5 on 2023-11-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_usertransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTransaction',
        ),
    ]
