# Generated by Django 4.2.5 on 2023-10-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_created_alter_order_is_ordered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Payments'},
        ),
    ]
