# Generated by Django 4.2.5 on 2023-10-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_alter_coupons_valid_from_alter_coupons_valid_to'),
        ('order', '0003_alter_payments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_app.coupons'),
        ),
    ]
