# Generated by Django 4.2.5 on 2023-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER CONFIRMED', 'ORDER CONFIRMED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
