# Generated by Django 4.2.5 on 2023-10-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RETURN REQUESTED', 'RETURN REQUESTED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('RETURN PROCESSING', 'RETURN PROCESSING'), ('SHIPPED', 'SHIPPED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
