# Generated by Django 4.2.5 on 2023-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_cancel_reason_order_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RETURN REQUESTED', 'RETURN REQUESTED'), ('DELIVERED', 'DELIVERED'), ('RETURN PROCESSING', 'RETURN PROCESSING'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('RETURNED', 'RETURNED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('ORDER CONFIRMED', 'ORDER CONFIRMED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
