# Generated by Django 4.2.5 on 2023-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RETURN PROCESSING', 'RETURN PROCESSING'), ('CANCELLED', 'CANCELLED'), ('RETURN REQUESTED', 'RETURN REQUESTED'), ('SHIPPED', 'SHIPPED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
