# Generated by Django 4.2.5 on 2023-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RETURN REQUESTED', 'RETURN REQUESTED'), ('RETURNED', 'RETURNED'), ('SHIPPED', 'SHIPPED'), ('RETURN PROCESSING', 'RETURN PROCESSING'), ('DELIVERED', 'DELIVERED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
