# Generated by Django 4.2.5 on 2023-10-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_is_returned_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('RETURN PROCESSING', 'RETURN PROCESSING'), ('RETURN REQUESTED', 'RETURN REQUESTED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('RETURNED', 'RETURNED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
