# Generated by Django 4.2.5 on 2023-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_is_returned_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('RETURNED', 'RETURNED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
