# Generated by Django 4.2.5 on 2023-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_discount_order_tax_order_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('RETURNED', 'RETURNED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
