# Generated by Django 4.2.5 on 2023-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('RETURNED', 'RETURNED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
