# Generated by Django 4.2.5 on 2023-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_shipping_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
