# Generated by Django 4.2.5 on 2023-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('RETURNED', 'RETURNED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
