# Generated by Django 4.2.5 on 2023-11-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('RETURNED', 'RETURNED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
