# Generated by Django 4.2.5 on 2023-11-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_order_shipping_remove_order_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('RETURNED', 'RETURNED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
