# Generated by Django 4.2.5 on 2023-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('RETURNED', 'RETURNED'), ('SHIPPED', 'SHIPPED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('DELIVERED', 'DELIVERED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
