# Generated by Django 4.2.5 on 2023-11-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('RETURNED', 'RETURNED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
