# Generated by Django 4.2.5 on 2023-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('DELIVERED', 'DELIVERED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('RETURNED', 'RETURNED'), ('SHIPPED', 'SHIPPED'), ('CANCELLED', 'CANCELLED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
