# Generated by Django 4.2.5 on 2023-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('CANCELLED', 'CANCELLED'), ('ORDER CONFIRMED', 'ORDER CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('RETURNED', 'RETURNED')], default='ORDER CONFIRMED', max_length=50),
        ),
    ]
